### PR TITLE
11.0 imp base tier validation 2

### PR DESCRIPTION
**Pull request by etobella**

### CODE REVIEW

**Comment by etobella** [comment]
Missing tests and readme on base_tier_validation_formula

**Comment by etobella** [comment]
@ageficent This is what we talked on the sprint code.
You can see an example of how to insert the widget automatically on:
https://github.com/tegin/hash-search/blob/11.0-add-hash_search/hash_search/models/hash_search_mixin.py#L91

**Comment by etobella** [comment]
@jbeficent

**Comment by AdriaGForgeFlow** [comment]
Commits being taken into account here https://github.com/OCA/server-ux/pull/55
Closing PR.

**Pull request closed without merging**
